export const techMap: { [key: string]: string } = {
    // --- LANGUAGES ---
    js: "devicon-javascript-plain", 
    javascript: "devicon-javascript-plain",
    ts: "devicon-typescript-plain",
    typescript: "devicon-typescript-plain",
    py: "devicon-python-plain",
    python: "devicon-python-plain",
    java: "devicon-java-plain",
    c: "devicon-c-plain",
    cpp: "devicon-cplusplus-plain",
    csharp: "devicon-csharp-plain",
    ruby: "devicon-ruby-plain",
    php: "devicon-php-plain",
    swift: "devicon-swift-plain",
    go: "devicon-go-plain",
    rust: "devicon-rust-plain",
    kotlin: "devicon-kotlin-plain",
    elixir: "devicon-elixir-plain",
    haskell: "devicon-haskell-plain",
    scala: "devicon-scala-plain",
    perl: "devicon-perl-plain",
    lua: "devicon-lua-plain",
    r: "devicon-r-plain",

    // --- FRONTEND FRAMEWORKS & LIBRARIES ---

    react: "devicon-react-original",
    reactjs: "devicon-react-original",
    vuejs: "devicon-vuejs-plain",
    angular: "devicon-angularjs-plain",
    svelte: "devicon-svelte-plain",
    solidjs: "devicon-solidjs-plain",
    alpinejs: "devicon-alpinejs-plain",
    jquery: "devicon-jquery-plain",
    redux: "devicon-redux-original",
    pinia: "devicon-pinia-plain", 
    threejs: "devicon-threejs-original",

    // --- BACKEND FRAMEWORKS ---
    nodejs: "devicon-nodejs-plain",
    nextjs: "devicon-nextjs-original-wordmark",
    express: "devicon-express-original",
    nestjs: "devicon-nestjs-plain",
    django: "devicon-django-plain",
    flask: "devicon-flask-original",
    fastapi: "devicon-fastapi-plain",
    spring: "devicon-spring-plain",
    laravel: "devicon-laravel-plain",
    rails: "devicon-rails-plain",
    phoenix: "devicon-phoenix-plain",
    deno: "devicon-deno-plain",
    bun: "devicon-bun-plain",

    // --- MOBILE DEVELOPMENT ---
    reactnative: "devicon-react-native-plain",
    flutter: "devicon-flutter-plain",
    ionic: "devicon-ionic-original",
    dart: "devicon-dart-plain",

    // --- DATABASES & CACHING ---
    mongodb: "devicon-mongodb-plain",
    postgresql: "devicon-postgresql-plain",
    mysql: "devicon-mysql-plain",
    sqlite: "devicon-sqlite-plain",
    redis: "devicon-redis-plain",
    cassandra: "devicon-cassandra-plain",
    couchdb: "devicon-couchdb-plain",
    mariadb: "devicon-mariadb-plain",
    neo4j: "devicon-neo4j-plain",
    supabase: "devicon-supabase-plain",
    prisma: "devicon-prisma-original",
    firebase: "devicon-firebase-plain",

    // --- STYLING & DESIGN ---
    html5: "devicon-html5-plain",
    html: "devicon-html5-plain",
    css3: "devicon-css3-plain",
    css: "devicon-css3-plain",
    tailwindcss: "devicon-tailwindcss-original",
    tailwind: "devicon-tailwindcss-original",
    sass: "devicon-sass-original",
    less: "devicon-less-plain-wordmark",
    lesscss: "devicon-less-plain-wordmark",
    bootstrap: "devicon-bootstrap-plain",
    figma: "devicon-figma-plain",
    photoshop: "devicon-photoshop-plain",
    illustrator: "devicon-illustrator-plain",
    xd: "devicon-xd-plain",

    // --- DEVOPS & CLOUD ---
    docker: "devicon-docker-plain",
    kubernetes: "devicon-kubernetes-plain",
    terraform: "devicon-terraform-plain",
    ansible: "devicon-ansible-plain",
    aws: "devicon-amazon-web-services-plain",
    googlecloud: "devicon-googlecloud-plain",
    azure: "devicon-azure-plain",
    digitalocean: "devicon-digitalocean-original",
    heroku: "devicon-heroku-original",
    netlify: "devicon-netlify-plain",
    vercel: "devicon-vercel-original",
    nginx: "devicon-nginx-original",
    apache: "devicon-apache-plain",

    // --- TOOLS, TESTING & CMS ---
    git: "devicon-git-plain",
    github: "devicon-github-plain",
    gitlab: "devicon-gitlab-plain",
    bitbucket: "devicon-bitbucket-plain",
    jest: "devicon-jest-plain",
    mocha: "devicon-mocha-plain",
    cypress: "devicon-cypress-plain",
    puppeteer: "devicon-puppeteer-plain",
    webpack: "devicon-webpack-plain",
    vite: "devicon-vitejs-plain",
    postman: "devicon-postman-plain",
    jenkins: "devicon-jenkins-line",
    graphql: "devicon-graphql-plain",
    wordpress: "devicon-wordpress-plain",
    strapi: "devicon-strapi-plain",
    linux: "devicon-linux-plain",
    bash: "devicon-bash-plain"
};